# Generated by Django 5.1.6 on 2025-02-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age',
            field=models.CharField(choices=[('1', '1-3'), ('2', '4-6'), ('3', '7-9'), ('4', '10-12')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/images/book_default.jpg', upload_to='book/'),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='Summary'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField(default=False)),
                ('review', models.CharField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
        ),
    ]
