# Generated by Django 5.1.6 on 2025-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book_age_book_image_book_name_book_recommend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(default='Review'),
        ),
    ]
