# Generated by Django 5.1.6 on 2025-02-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_book_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/images/book_default.jpg', upload_to=''),
        ),
    ]
