# Generated by Django 5.1.6 on 2025-02-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='Book Title', max_length=1000),
        ),
    ]
